
# resolver: lts-9.20  # ghc-8.0.2
# resolver: lts-11.12 # ghc-8.2.2
# resolver: lts-12.19 # ghc-8.4.4
resolver: lts-13.4 # ghc-8.6.3

extra-deps:
  - ShowF-0.1.1
  - type-unary-0.3.2
  - applicative-numbers-0.1.3
  - ty-0.1.7
